### ISSUE TITLE
Handle errors when calling ClubHouse API

### ISSUE THREAD

**Issue by andjosh** [andjosh/clubhouse-cli#4]
Right now, there is very minimal, or absent, error handling for API calls. It would be nice to catch those and return a readable error to the user.

**Comment by andjosh** [comment]
For example: 

~~~sh
$ club
Loading workspace default: --owner 'josh' --state 'edule|evelop|review|fail'

Error fetching stories: { FetchError: invalid json response body at https://api.clubhouse.io/api/beta/members?token=<token> reason: Unexpected token < in JSON at position 0
    at /usr/local/lib/node_modules/clubhouse-cli/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at https://api.clubhouse.io/api/beta/members?token=59e10a0a-3169-44ef-8a0b-f95280b10dcf reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
$ curl https://api.clubhouse.io/api/beta/members?token=<token>
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

~~~

**Comment by andjosh** [comment]
That error should probably be handled and correctly thrown in the `clubhouse-lib`

**Comment by andjosh** [comment]
Necessary first step: https://github.com/clubhouse/clubhouse-lib/pull/21
