### ISSUE TITLE
Bug: not a git repository

### ISSUE THREAD

**Issue by rakusan2** [andjosh/clubhouse-cli#79]
### Expected Behavior
Expecting to View Stories
### Actual Behavior
```
$ club story
Loading... ⣾ fatal: not a git repository (or any of the parent directories): .git
(node:22132) UnhandledPromiseRejectionWarning: Error: Command failed: git branch
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.<anonymous> (/usr/lib/node_modules/clubhouse-cli/build/bin/club-story.js:141:46)
    at step (/usr/lib/node_modules/clubhouse-cli/build/bin/club-story.js:33:23)
    at Object.next (/usr/lib/node_modules/clubhouse-cli/build/bin/club-story.js:14:53)
    at fulfilled (/usr/lib/node_modules/clubhouse-cli/build/bin/club-story.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:22132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Loading... ⣽
```
### Steps to Reproduce
```
npm -g install clubhouse-cli
club install
club story
```

**Comment by andjosh** [comment]
Yeah - this happens because the command was not passed a story ID, so it tries to pull the story ID from a git branch. We should catch the lack of a git repo and just exit.

**Comment by rakusan2** [comment]
In the --help there is also no indication that an ID needs to be passed

**Comment by andjosh** [comment]
Currently, it is the first line of the usage in `--help`:
```
Usage: club-story [options] <id>
```

**Comment by rakusan2** [comment]
Sorry I was looking at `club --help`
